# ESTO ES UN COMENTARIO DE UNA SOLA LÍNEA

# DECLARACIÓN DE UNA VARIABLE
nombre = "Juan"  # SE ASIGNA UN NOMBRE A LA VARIABLE

# COMENTARIO DE UNA SOLA LÍNEA AL LADO DE UNA INSTRUCCIÓN

edad = 25  # ESTO ES LA EDAD DE JUAN

# COMENTARIOS MULTILÍNEA

"""
ESTE ES UN COMENTARIO MULTILÍNEA
PUEDES UTILIZARLO PARA EXPLICACIONES MÁS LARGAS
QUE NO NECESITAN SER PARTE DEL CÓDIGO EJECUTABLE.
"""

# COMENTARIO EN UNA FUNCIÓN

def saludar():
    # SE IMPRIME UN MENSAJE DE SALUDO
    print("¡Hola, bienvenido!")

# LLAMAMOS A LA FUNCIÓN
saludar()