# FRAGMENTOS DE CADENAS: CONCATENACIÓN Y OPERACIONES BÁSICAS

# DEFINIMOS DOS FRAGMENTOS DE CADENAS
fragmento1 = "La programación es como la vida:"  # FRAGMENTO 1
fragmento2 = "llena de errores, pero también de posibilidades."  # FRAGMENTO 2

# CONCATENAMOS LOS DOS FRAGMENTOS DE CADENAS
frase_completa = fragmento1 + fragmento2  # SE UNE EL FRAGMENTO 1 Y 2

# IMPRIMIMOS LA CADENA COMPLETA
print(frase_completa)  # SE MUESTRA LA CADENA UNIDA

# SEGUNDO EJEMPLO DE CONCATENACIÓN CON UN ESPACIO ADICIONAL
frase_completa = fragmento1 + " " + fragmento2  # AÑADIMOS UN ESPACIO ENTRE LOS FRAGMENTOS

# IMPRIMIMOS LA CADENA CON ESPACIO ADICIONAL
print(frase_completa)  # SE MUESTRA LA CADENA CON ESPACIO

# USO DE COMILLAS SIMPLES Y DOBLES EN CADENAS

# CADENA CON COMILLAS SIMPLES
print('"El tiempo es oro", me dijo.')  # USAMOS COMILLAS SIMPLES EN UNA CADENA

# CADENA CON COMILLAS DOBLES ESCAPADAS
print("\"El tiempo es oro\", me dijo.")  # USAMOS COMILLAS DOBLES ESCAPADAS

# PARTE 1: SOLICITAR DATOS AL USUARIO Y MOSTRAR RESULTADOS

# SOLICITUD DE NOMBRE AL USUARIO
nombre = input("Por favor, introduzca su nombre:\n")  # SOLICITAMOS EL NOMBRE AL USUARIO

# INCRUSTACIÓN DEL NOMBRE EN UNA CADENA
print(f"Hola, {nombre}. Tenga un maravilloso día.")  # USAMOS F-STRING PARA INCLUIR EL NOMBRE EN EL MENSAJE

# SOLICITUD DE NOMBRE AL USUARIO
nombre = input("Por favor, introduzca su nombre:\n")  # SOLICITAMOS EL NOMBRE AL USUARIO

# CONCATENACIÓN DE CADENAS PARA MOSTRAR MENSAJE
print("Hola, " + nombre + ". Tenga un maravilloso día.")  # CONCATENAMOS EL NOMBRE CON EL MENSAJE

# PARTE 2: OPERACIONES CON VARIABLES

# DEFINIMOS DOS VARIABLES NUMÉRICAS
a = 10
b = 30

# REALIZAMOS UNA SUMA Y LA INCLUIMOS EN UN F-STRING
resultado = f"La suma de {a} + {b} es: {a + b}"  # INCLUIMOS EL RESULTADO DE LA SUMA EN UNA CADENA

# IMPRIMIMOS EL RESULTADO DE LA SUMA
print(resultado)  # SE MUESTRA EL RESULTADO DE LA SUMA

# PARTE 3: MODIFICACIONES DE TEXTO

# DEFINIMOS UNA FRASE EN MINÚSCULAS
frase = "la imaginación es el principio de la creación."  # FRASE EN MINÚSCULAS

# CONVERTIMOS LA PRIMERA LETRA A MAYÚSCULA
frase_convertida = frase.capitalize()  # UTILIZAMOS 'capitalize()' PARA HACER MAYÚSCULA LA PRIMERA LETRA

# IMPRIMIMOS LA FRASE CON LA PRIMERA LETRA MAYÚSCULA
print(frase_convertida)  # SE MUESTRA LA FRASE CON LA PRIMERA LETRA EN MAYÚSCULA

# OBTENEMOS EL NOMBRE DEL USUARIO
nombre = input("Introduzca su nombre:\n")  # SOLICITAMOS EL NOMBRE AL USUARIO

# CONVERTIMOS LA PRIMERA LETRA DEL NOMBRE A MAYÚSCULA
nombre_convertido = nombre.capitalize()  # UTILIZAMOS 'capitalize()' PARA HACER MAYÚSCULA LA PRIMERA LETRA DEL NOMBRE

# IMPRIMIMOS UN MENSAJE CON EL NOMBRE CONVERTIDO
print(f"Hola {nombre_convertido}.")  # SE MUESTRA EL NOMBRE CON LA PRIMERA LETRA EN MAYÚSCULA

# DEFINIMOS UNA FRASE CON LETRAS EN MAYÚSCULA Y MINÚSCULA
frase = "lA imAgiNAción ES el pRincipiO de LA CREAción."  # FRASE CON MAYÚSCULAS Y MINÚSCULAS MIXTAS

# CONVERTIMOS TODAS LAS LETRAS A MINÚSCULAS
frase_convertida = frase.lower()  # UTILIZAMOS 'lower()' PARA HACER TODAS LAS LETRAS MINÚSCULAS

# IMPRIMIMOS LA FRASE CON TODAS LAS LETRAS EN MINÚSCULAS
print(frase_convertida)  # SE MUESTRA LA FRASE EN MINÚSCULAS
